name: Fuxion E2E Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Corre todos los días a las 6 AM UTC (opcional)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permite correrlo manualmente desde un botón en GitHub

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar Dependencias (NPM)
      run: npm install

    - name: Instalar Navegadores de Playwright con librerías gráficas
      run: npx playwright install --with-deps

    - name: Correr Pruebas (Automáticas)
      run: npx playwright test --project=Mexico --project=Argentina

    - name: Guardar Reporte como Artefacto (Descargable)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Publicar Reporte Interactivo en GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages
        keep_files: false
